### ISSUE TITLE
Is there any way to install sigopt[lite]==8.8.0 on Python 3.7?

### ISSUE THREAD

**Issue by NingWang5** [sigopt/sigoptlite#26]
When running `pip install 'sigopt[lite]'==8.8.0` on Python 3.7, the following error will be reported:

> ERROR: Ignored the following versions that require a different python version: 0.1.1 Requires-Python >=3.10; 0.1.2 Requires-Python >=3.10
> ERROR: Could not find a version that satisfies the requirement sigoptlite>=0.1.1; extra == "lite" (from sigopt[lite]) (from versions: 0.1)
> ERROR: No matching distribution found for sigoptlite>=0.1.1; extra == "lite"

Is there any way to install sigopt[lite]==8.8.0 on Python 3.7？

**Comment by malkomes** [comment]
Our system uses Python `3.10` at the moment (dev, tests, etc.), and support for Python `3.7` ends in 2 months, so we recommend using Python `>=3.10`.

Feel free to reach out via email if you have any questions; we will be happy to help!
